In [1]:
import numpy as np

In [2]:
1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
vector=np.zeros(10)
print(vector)
vector[4]=1
print("After Making the changes")
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After Making the changes
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
2. Create a vector with values ranging from 10 to 49.

In [3]:
vec=np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
matrix=np.random.randint(0,9,(3,3))
print(matrix)

[[2 4 8]
 [6 3 0]
 [1 0 2]]


In [ ]:
4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
elements=np.array([1,2,0,0,4,0])
non=elements>0
print(elements[non])

[1 2 4]


In [ ]:
5. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
array=np.random.randint(0,100,(10,10))
print(array)
m=np.max(array)
print("maximum:",m)
n=np.min(array)
print("minimum:",n)

[[53 91 64 92 21 88 92 16 52 99]
 [45 90 37 49 96 60 95 25 71 14]
 [18 69  7  0 53  2  4  6 94 74]
 [72 41 85 77 64 40 37 97 55 59]
 [ 6 54 97 13 16 10 16 56 26 80]
 [28 28 34 26 56 40 31 76 41 13]
 [61 35 37 24  8 55  1 22 67 14]
 [65  5 28 92 54 10 69 88 87 45]
 [48 33 67 43 50 76 96  5  1 69]
 [43 96 95 14 62 47 55 91  1 96]]
maximum: 99
minimum: 0


In [ ]:
6. Create a random vector of size 30 and find the mean value.

In [7]:
vector=np.random.rand(30)
print(vector)
np.mean(vector)

[0.93100896 0.53704918 0.17908694 0.98493199 0.50875574 0.38452833
 0.69169332 0.82608784 0.52975273 0.6413538  0.81528971 0.90057177
 0.84759135 0.65376935 0.20847213 0.09746461 0.93269259 0.5950502
 0.88043099 0.85807728 0.57697222 0.42550428 0.87276535 0.75532979
 0.0933463  0.44093519 0.74122686 0.85319552 0.26678791 0.67502824]


0.6234916812841516